### ISSUE TITLE
点击“转换并下载”文件无法下载

### ISSUE THREAD

**Issue by maplefz** [sorz/asstosrt#7]
不知道还会不会花精力更新在线版，但是尝试了edge、chrome和firefox，都是点“转换并下载”后，转换后的文件直接是在网页显示，而不是下载文件（是不是浏览器要哪里设置，但是3个浏览器都这样），转换后显示的网址：https://lab.sorz.org/tools/asstosrt/convert/AAAA.srt

**Comment by sorz** [comment]
修好啦，谢谢反馈

**Comment by maplefz** [comment]
好像还是有bug，比如文件名里有#，会把文件名中的#及后面的字符删掉，而且没有文件后缀

**Comment by maplefz** [comment]
不过发现了asstosrt-wasm这个项目能用，两个项目有什么不一样吗？

**Comment by sorz** [comment]
> 比如文件名里有#

也修好啦

> 不过发现了asstosrt-wasm这个项目能用

这个应该会更稳定一些，老项目需要上传服务器处理，新项目直接在浏览器本地转换
